# Generated by Django 3.2.10 on 2021-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Beton:')),
                ('description', models.CharField(max_length=256, verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Zastosowanie')),
                ('conc', models.ManyToManyField(related_name='uses', to='calc.Concrete')),
            ],
        ),
    ]
