# Generated by Django 3.2.10 on 2021-12-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_rename_days_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='descriptions',
            new_name='description',
        ),
    ]
