# Generated by Django 3.2.10 on 2021-12-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_list_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='concrete_pomp',
            field=models.BooleanField(null=True, verbose_name='Pompa do betonu'),
        ),
        migrations.AlterField(
            model_name='list',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefon'),
        ),
    ]
